server:
  port: 8082

spring:
  application:
    name: admin-server 
          
eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: false  
      
management:
  endpoint:
    health:
      show-details: always